---
- name: Create virtual environments
  ansible.builtin.shell: >
    mkvirtualenv {{ item.env_name }}
  environment:
    WORKON_HOME: "{{ item.workon_home }}"
    VIRTUALENVWRAPPER_PYTHON: "{{ item.virtualenvwrapper_python | default(default_python_path) }}"
    VIRTUALENVWRAPPER_SCRIPT: "{{ item.virtualenvwrapper_script | default(default_virtualenvwrapper_path) }}"
  args:
    chdir: "{{ ansible_env.HOME }}"
  when: virtualenv_action == 'create' and item.env_name is defined
  ignore_errors: true
  become: true
  become_user: "{{ virtualenvwrapper_user }}"
  loop: "{{ virtualenv_settings }}"



