---

# Debug the file
- name: Debug each env_item
  ansible.builtin.debug:
    var: env_item
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: env_item

- name: Debug virtualenv_action
  ansible.builtin.debug:
    var: virtualenv_action

- name: Create virtual environments
  ansible.builtin.shell: >
    "mkvirtualenv -a '{{ env_item.project_home }}' {{ env_item.env_name }}"
  environment:
    WORKON_HOME: "{{ env_item.workon_home }}"
    VIRTUALENVWRAPPER_PYTHON: "{{ env_item.virtualenvwrapper_python | default(default_python_path) }}"
    VIRTUALENVWRAPPER_SCRIPT: "{{ env_item.virtualenvwrapper_script | default(default_virtualenvwrapper_path) }}"
    PROJECT_HOME: "{{ env_item.project_home | default(default_project_home) }}"
  args:
    chdir: "{{ ansible_env.HOME }}"
  when: virtualenv_action == 'create' and env_item.env_name is defined and env_item.project_home is defined
  ignore_errors: true
  become: true
  become_user: "{{ virtualenvwrapper_user }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: env_item
