---
# Debug the entire env_item
- name: Debug each env_item
  ansible.builtin.debug:
    var: env_item
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: env_item

# Debug virtualenv_action
- name: Debug virtualenv_action
  ansible.builtin.debug:
    var: virtualenv_action

# Debug env_name from the nested dictionary
- name: Debug env_name
  ansible.builtin.debug:
    msg: "env_name for {{ project_key }} is {{ project_value.env_name }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: project_item
  vars:
    project_key: "{{ project_item.keys() | first }}"
    project_value: "{{ project_item[project_key] }}"

# Debug project_home from the nested dictionary
- name: Debug project_home
  ansible.builtin.debug:
    msg: "project_home for {{ project_key }} is {{ project_value.project_home }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: project_item
  vars:
    project_key: "{{ project_item.keys() | first }}"
    project_value: "{{ project_item[project_key] }}"

- name: debug the when statement
  ansible.builtin.debug:
    msg: | 
     "this is our values: 
     virtualenv_action == {{ virtualenv_action }}"
     project_value.env_name == "{{ project_value.env_name }}"
     project_value.project_home == "{{ project_value.project_home }}" 
  when: 
    - virtualenv_action == 'create' 
#    - project_value.env_name is defined 
#    - project_value.project_home is defined
  ignore_errors: true
  become: true
  become_user: "{{ virtualenvwrapper_user }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: project_item
  vars:
    project_key: "{{ project_item.keys() | first }}"
    project_value: "{{ project_item[project_key] }}"

- name: Echo values | Create virtual environments
  ansible.builtin.command:
    cmd: >
      echo "Creating environment: {{ project_value.env_name }} in {{ project_value.project_home }} with Python: {{ project_value.virtualenvwrapper_python | default(default_python_path) }}"
  environment:
    WORKON_HOME: "{{ project_value.workon_home }}"
    VIRTUALENVWRAPPER_PYTHON: "{{ project_value.virtualenvwrapper_python | default(default_python_path) }}"
    VIRTUALENVWRAPPER_SCRIPT: "{{ project_value.virtualenvwrapper_script | default(default_virtualenvwrapper_path) }}"
    PROJECT_HOME: "{{ project_value.project_home | default(default_project_home) }}"
  #args:
  #  chdir: "{{ ansible_env.HOME }}"
  when: 
    - virtualenv_action == 'create' 
    - project_value.env_name is defined 
    - project_value.project_home is defined
  ignore_errors: true
  become: true
  become_user: "{{ virtualenvwrapper_user }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: project_item
  vars:
    project_key: "{{ project_item.keys() | first }}"
    project_value: "{{ project_item[project_key] }}"

- name: Print ansible_env.HOME
  debug:
    var: ansible_env.HOME


- fail:

- name: Create virtual environments
  ansible.builtin.shell: >
    "mkvirtualenv -a '{{ project_details.project_home }}' {{ project_details.env_name }}"
  environment:
    WORKON_HOME: "{{ project_details.workon_home }}"
    VIRTUALENVWRAPPER_PYTHON: "{{ project_details.virtualenvwrapper_python | default(default_python_path) }}"
    VIRTUALENVWRAPPER_SCRIPT: "{{ project_details.virtualenvwrapper_script | default(default_virtualenvwrapper_path) }}"
    PROJECT_HOME: "{{ project_details.project_home | default(default_project_home) }}"
  args:
    chdir: "{{ ansible_env.HOME }}"
  when: 
    - virtualenv_action == 'create' 
    - project_details.env_name is defined 
    - project_details.project_home is defined
  ignore_errors: true
  become: true
  become_user: "{{ virtualenvwrapper_user }}"
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: project_details
    extended: yes
  vars:
    project_details: "{{ env_item.values() | first }}"

