---
- name: Install virtualenvwrapper
  ansible.builtin.pip:
    name: virtualenvwrapper
    state: present

- name: Setup virtualenvwrapper script
  ansible.builtin.template:
    src: virtualenvwrapper.sh.j2
    dest: "{{ script_item.virtualenvwrapper_script | default(default_virtualenvwrapper_path) }}"
    mode: '0755'
  loop: "{{ virtualenv_settings }}"
  loop_control:
    loop_var: script_item
  when: script_item.virtualenvwrapper_script is defined or default_virtualenvwrapper_path is defined

- name: Manage virtual environments
  include_tasks: "{{ man_item.task_file }}"
  loop: "{{ virtualenv_tasks }}"
  loop_control:
    loop_var: man_item
  when: man_item.condition

